name:cppcheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: get-ccpcheck
      run:  sudo apt-get install cppcheck
    - name: cppcheck
      run: make -C 3_Implementation/ analysis
  
